<?xml version="1.0" encoding="utf-8"?><Database Name="EdwardsFoundation" Class="ExamSystemDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=C:\Dev\EdwardsFoundation\EdwardsFoundation.mdf;Integrated Security=True;Connect Timeout=30;User Instance=True" SettingsObjectName="JoanCEdwards.DAO.Properties.Settings" SettingsPropertyName="EdwardsFoundationConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Choice" Member="Choices">
    <Type Name="Choice">
      <Column Name="ChoiceId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Label" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Choice_QuestionChoice" Member="QuestionChoices" ThisKey="ChoiceId" OtherKey="ChoiceId" Type="QuestionChoice" />
    </Type>
  </Table>
  <Table Name="dbo.UserProfile" Member="UserProfiles">
    <Type Name="UserProfile">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="EmailAddress" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="UserType" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="GradeLevel" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Association Name="UserProfile_ExamResult" Member="ExamResults" ThisKey="UserId" OtherKey="UserId" Type="ExamResult" />
      <Association Name="UserProfile_QuestionAnswer" Member="QuestionAnswers" ThisKey="UserId" OtherKey="UserId" Type="QuestionAnswer" />
    </Type>
  </Table>
  <Table Name="dbo.ExamQuestions" Member="ExamQuestions">
    <Type Name="ExamQuestion">
      <Column Name="ExamId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QuestionId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Question_ExamQuestion" Member="Question" ThisKey="QuestionId" OtherKey="QuestionId" Type="Question" IsForeignKey="true" />
      <Association Name="Exam_ExamQuestion" Member="Exam" ThisKey="ExamId" OtherKey="ExamId" Type="Exam" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Question" Member="Questions">
    <Type Name="Question">
      <Column Name="QuestionId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="QuestionCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="QuestionType" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="QuestionText" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Question_ExamQuestion" Member="ExamQuestions" ThisKey="QuestionId" OtherKey="QuestionId" Type="ExamQuestion" />
      <Association Name="Question_QuestionChoice" Member="QuestionChoices" ThisKey="QuestionId" OtherKey="QuestionId" Type="QuestionChoice" />
      <Association Name="Question_QuestionAnswer" Member="QuestionAnswers" ThisKey="QuestionId" OtherKey="QuestionId" Type="QuestionAnswer" />
    </Type>
  </Table>
  <Table Name="dbo.QuestionChoice" Member="QuestionChoices">
    <Type Name="QuestionChoice">
      <Column Name="QuestionId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ChoiceId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Choice_QuestionChoice" Member="Choice" ThisKey="ChoiceId" OtherKey="ChoiceId" Type="Choice" IsForeignKey="true" />
      <Association Name="Question_QuestionChoice" Member="Question" ThisKey="QuestionId" OtherKey="QuestionId" Type="Question" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ExamResult" Member="ExamResults">
    <Type Name="ExamResult">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ExamId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserScore" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaxScore" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="UserProfile_ExamResult" Member="UserProfile" ThisKey="UserId" OtherKey="UserId" Type="UserProfile" IsForeignKey="true" />
      <Association Name="Exam_ExamResult" Member="Exam" ThisKey="ExamId" OtherKey="ExamId" Type="Exam" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Exam" Member="Exams">
    <Type Name="Exam">
      <Column Name="ExamId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Instructions" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Exam_ExamQuestion" Member="ExamQuestions" ThisKey="ExamId" OtherKey="ExamId" Type="ExamQuestion" />
      <Association Name="Exam_ExamResult" Member="ExamResults" ThisKey="ExamId" OtherKey="ExamId" Type="ExamResult" />
      <Association Name="Exam_QuestionAnswer" Member="QuestionAnswers" ThisKey="ExamId" OtherKey="ExamId" Type="QuestionAnswer" />
    </Type>
  </Table>
  <Table Name="dbo.QuestionAnswer" Member="QuestionAnswers">
    <Type Name="QuestionAnswer">
      <Column Name="QuestionId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Answer" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ExamId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Score" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Exam_QuestionAnswer" Member="Exam" ThisKey="ExamId" OtherKey="ExamId" Type="Exam" IsForeignKey="true" />
      <Association Name="Question_QuestionAnswer" Member="Question" ThisKey="QuestionId" OtherKey="QuestionId" Type="Question" IsForeignKey="true" />
      <Association Name="UserProfile_QuestionAnswer" Member="UserProfile" ThisKey="UserId" OtherKey="UserId" Type="UserProfile" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.DeleteUser" Method="DeleteUser">
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteExam" Method="DeleteExam">
    <Parameter Name="ExamId" Parameter="examId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>