//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamApplication {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExamAppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExamAppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExamApplication.ExamAppResources", typeof(ExamAppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string clearButtonText {
            get {
                return ResourceManager.GetString("clearButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter you Email Address to recieve your password..
        /// </summary>
        internal static string labelControlPasswordRecoveryInstruction {
            get {
                return ResourceManager.GetString("labelControlPasswordRecoveryInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is a required field..
        /// </summary>
        internal static string labelEmailAddressRequired {
            get {
                return ResourceManager.GetString("labelEmailAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name is a required field..
        /// </summary>
        internal static string labelFirstNameRequired {
            get {
                return ResourceManager.GetString("labelFirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name is a required field..
        /// </summary>
        internal static string labelLastNameRequired {
            get {
                return ResourceManager.GetString("labelLastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Email.
        /// </summary>
        internal static string labelSearchUsersTextBox {
            get {
                return ResourceManager.GetString("labelSearchUsersTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address is invalid..
        /// </summary>
        internal static string lableEmailAddressInvalid {
            get {
                return ResourceManager.GetString("lableEmailAddressInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade Level is a required field..
        /// </summary>
        internal static string lableGradeLevelRequired {
            get {
                return ResourceManager.GetString("lableGradeLevelRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Users.
        /// </summary>
        internal static string lableSearchUsersSearchButton {
            get {
                return ResourceManager.GetString("lableSearchUsersSearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your User Name or Password is Invalid.
        /// </summary>
        internal static string loginControlAuthenticationFailed {
            get {
                return ResourceManager.GetString("loginControlAuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string loginControlPasswordLabel {
            get {
                return ResourceManager.GetString("loginControlPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        internal static string loginControlPasswordRecoverLabel {
            get {
                return ResourceManager.GetString("loginControlPasswordRecoverLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string loginControlUserNameLabel {
            get {
                return ResourceManager.GetString("loginControlUserNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string logoutLinkLabel {
            get {
                return ResourceManager.GetString("logoutLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Users.
        /// </summary>
        internal static string pageTitlesAdministerUsers {
            get {
                return ResourceManager.GetString("pageTitlesAdministerUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dash Board.
        /// </summary>
        internal static string pageTitlesDashBoard {
            get {
                return ResourceManager.GetString("pageTitlesDashBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        internal static string pageTitlesForgotPassword {
            get {
                return ResourceManager.GetString("pageTitlesForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string pageTitlesLoginPage {
            get {
                return ResourceManager.GetString("pageTitlesLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string submitButtonText {
            get {
                return ResourceManager.GetString("submitButtonText", resourceCulture);
            }
        }
    }
}
